apiVersion: v1
data:
    client-info-template.yaml: ENC[AES256_GCM,data:ZrVozPbhZpMekQdCpXeOQEWepTZzBhu+tNirM+Cixyw/0NTuGFy0iD0LQB/o02A90gLvhEY+xuVW6VQA2I6edEkn9miyezRe0Mh0vyHnDG7kl1bxqHln4Thx8z+rTULghCM6nklVJMz/0LTXkhcM1VvHDGpAGryhBCG57bHOgewCGOZOMaosTKKNqNdbC8ZTS34GV3I+5vNVmMogt/z5CbNJMJ657P+aY+hT4vle1xLoH2TgASQDsFZMSJBQpFAEbQm9yzaAr3y/2X2z+IV5DHSxhALRJJocjNYd4vFB5Z5XTB/q4/E3hFW35Sa/OlI+dG8i6dGxAuhLw6nwwEBqdybfvgH8edP9ZSHGSlW0Nn2OM1U+B5kiC0EcB5hqgVdkM0RCN2yUSkQhaGq8LquYtkOzJVHxHdPpZA1hKMtbHnjdxrRWzr7zaJKfzfmtVeY0NlzRqgXeLvpFn/vwVa0whB3TKLgzmNGpVzlXHfs+Y0BFsK9Q3TyDV6PjB+jtfRCu5mjmf5zVAOz4yNNAvNiE/OBXbNLZbv3sELFkEBmzkGjOvMup3y3f+KMPGk4+9io91gp3jJQBbjjGtbKlTYLI6MH02KicXUrMlez6dAbm+rcR56czMdKqYlDTIhx4qDds5pR2leVZWjmt4H49GubAGKXhZvqC11fH695jpHIRSxIxOmYpYhhbCi4RXfRRYWTa5QQiYdsW5lOXagcuyszNamm9EfEFX4LxGX0B7X3DygZkWDOVbqmm2hw0XG9ncxvWncYu8sNZuCqgCo8j,iv:np3RaqwZ0ODq2VwOhFXlbJeGm0GRhosQ57MEI+eO/CU=,tag:gmia6CEkILBV82gy9OTJzw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: client-info-secret
    namespace: synology-csi
sops:
    age:
        - recipient: age19ktsh93hekpjk5cwjex3njgl9fyxtsfd3lz49khjwxtnlk8ucc6qeqad4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeDIwK05STlNSU2l5VGZN
            UFpKaXB4U3RHRWl0Y2o1cUlEYkJuRUZacENBCmJ6clc5MjArUUNPNmJ2blVBc1NK
            U01pTGN2UUhwWlR5NFhHT09TSWVMWWMKLS0tIGpEeVU0MHRRMGd5Tk5uTy9BSVE4
            SGlGbjlvaWhmQkJEWG03QjZ5bEE1VFkKjdnHyqe6FumZbTHFFEYgckqB922ZTxA8
            XwjjcGX3WG8q6t2+Yw/jZ2ODFv6PhUODpTfhqivzPQNqyanOMJVoNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-11T19:28:08Z"
    mac: ENC[AES256_GCM,data:htElGdD3iyXuBIGsKkiQGDKVXpFSPj5JXi6aiJ3fHQU5gBlAVSP09T3ZZ/Q50EwudLqGC6kTd9beV9vz5oV6MYkRlru1Rg7sAFME8x5aWV4jvd4lIJXLHTLl8z5hFPQEX5GxpTezBDgpMQt13qQLGA2bWf+6oPGb1VQpLM4xDMA=,iv:4DryUUb75dHngZ6vKq8B3zj82biC5YgUNyyNpMuvZao=,tag:6HSkVuHqQaf1keVTDW2twg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
