apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-data-pvc
spec:
  storageClassName: synology-iscsi
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  securityContext:
    fsGroup: 5050