apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:u19FUkCIaYezKhxc,iv:kfqN1ixpNSS05r7H5NuG+nfFQv5janoWItd8T3CoMEA=,tag:N4HR4t+dv5dhahsjsYEeyg==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:pbBYoZ0HtcR60Rw/WmGQuQ==,iv:8BfgvIR6aDuZ3dOWvgWUUN4z2XY97mjWAuRVS4iJlpc=,tag:ixpo38AoUw4MIvadPNfpTQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-container-env
sops:
    age:
        - recipient: age19ktsh93hekpjk5cwjex3njgl9fyxtsfd3lz49khjwxtnlk8ucc6qeqad4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWS9pT2xSSURyMk92MjMx
            WDZsbG5SVHV0Z2xZN1gvZ0RrdTljRmRUUVM4CjJVRU5CSVd5WnFkcHVIYUFyNjQr
            VmpwOGlYUkovVmJPVVQrdUF5MnlFN1UKLS0tIFo3ZGh2OUxDMjRULzNKMzFhMTRM
            YkdCblNDWXJ3eGM3eEVxWVIrTGhJeFkKBa+fx5R4cwWYmUvDEaHrL9fwPNPKLcXK
            srnQvbJrT3SuzXWyB5YqvCKlRJzKWNNeKuoXQ9jssKe30aHQT89A+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-01T01:23:35Z"
    mac: ENC[AES256_GCM,data:p4W5GK+PeiILQ5Di1dY6tpFZK+KswSnI4fqA73xTmQgyOUjWCpwRxwnlAFsJNoHG/5F6Ug4sGCShO+c/s87+hgalSIhb+MMdqXB8mATwlBMCOkA863QhxY+Tgo5MH2v1iQbnh3MOnMhmLx8x5VuMauA0F3Yf70rVSY7BePh89h8=,iv:cVz0qGBHEz1l0KQJRi20F7fKpc51TliyPl5TLJ4f02k=,tag:hG1LISwxHsGdSgXjYZcIjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
