apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:AVyKXWdroroM+4kO,iv:V/9nAjW5qZ1wHFn8ytTRdvXxe7bwphLXyoAvuqemHs8=,tag:1Vaj9lOlO53j2b5/htDXNA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:kwxBtvmQWZMh3AE6OAOPfQ==,iv:7V1y3529tGciHJc20c0O2YvJyRyDvHOIrkwhUDoAPKM=,tag:LeQ84n0pu8vqhVTZ5geajg==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age19ktsh93hekpjk5cwjex3njgl9fyxtsfd3lz49khjwxtnlk8ucc6qeqad4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYT2x6NU1KSzBEdUcvdjU0
            S1hzSlFJTGhyWmU5SkhoYmUrT0IydU1NdnprCkd6bHhkRnNXM2NJc2NlOFZOUHM1
            aW10Ym9GZFFObTVPUENGcFMyeFBQZU0KLS0tIGVCTzEwVXQ2YjRyc2tEOUdMakwy
            Tk91SkdaM1o0NWFaYnI1R1JFSlJFaTQKRwrZT//rl2zPEG60dXcGIBSR2onFFZ42
            uSgPHTGD7F7aCLEtlidrqzyw7BlpVjzncVhzGT8FTStEMcjkNAdrZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-01T01:55:43Z"
    mac: ENC[AES256_GCM,data:0k8yck1kij0f0WZwoEKh9X9LopV4lxWlwsdUgRy52UHfV653OwLQyogKeoASZkkid7bEnBL/C5ZEx/CyZdl8Js2DKAl8C/tgLBzNzIqe62hFTbTE9c4S8GGGZOOPzAdtDCSYUaAekDPATlwRdZJnVlNz6U5Nn+2wM3Pww8/4uRE=,iv:s4CODoUeX+9ZoFhFFxa4Bx9czAs6muJKSzBaBAK10+c=,tag:/25NM/rVhUOJ6A9cjNgi8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
