---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: max
spec:
  # strategy:
  #   type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: max
  template:
    metadata:
      labels:
        app: max
    spec:
      containers:
        - name: max
          image: modular/max-nvidia-full:latest
          args: ["--model-path", "modularai/llama-3.1-1L"]
          ports:
            - containerPort: 8000

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault

          resources:
            requests:
              memory: "8Gi"
              cpu: "250m"
            limits:
              memory: "12Gi"

          volumeMounts:
            - name: max-data
              mountPath: /root/.cache/huggingface

      volumes:
        - name: max-data
          persistentVolumeClaim:
            claimName: max-data-pvc
