apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "71.1.*"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  values:
    grafana:
      adminPassword: admin
      ingress:
        enabled: true

        # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
        # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
        ingressClassName: traefik

        ## Override ingress to a different defined port on the service
        # servicePort: 8081
        ## Override ingress to a different service then the default, this is useful if you need to
        ## point to a specific instance of the alertmanager (eg kube-prometheus-stack-alertmanager-0)
        # serviceName: kube-prometheus-stack-alertmanager-0

        ## Hosts must be provided if Ingress is enabled.
        ##
        hosts: 
          - grafana.kyjung.com
        

        ## Paths to use for ingress rules - one path should match the alertmanagerSpec.routePrefix
        ##
        paths: []
        # - /

        ## For Kubernetes >= 1.18 you should specify the pathType (determines how Ingress paths should be matched)
        ## See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#better-path-matching-with-path-types
        # pathType: ImplementationSpecific

        ## TLS configuration for Alertmanager Ingress
        ## Secret must be manually created in the namespace
        ##
        tls: []
        # - secretName: alertmanager-general-tls
        #   hosts:
        #   - alertmanager.example.com
