apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  # strategy:
  #   type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:

      securityContext:
        fsGroup: 33
        runAsUser: 33
        runAsGroup: 33

      containers:
        - name: linkding
          image: sissbruecker/linkding:1.40.0
          ports:
            - containerPort: 9090

          securityContext:
            allowPrivilegeEscalation: false

          envFrom:
            - secretRef:
                name: linkding-container-env
            - configMapRef:
                name: linkding-configmap

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"

          volumeMounts:
            - name: linkding-data
              mountPath: /etc/linkding/data

      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc

