apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data-pvc
spec:
  storageClassName: synology-iscsi
  resources:
    requests:
      storage: 512Mi
  accessModes:
    - ReadWriteMany
  securityContext:
    fsGroup: 33