apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data-pvc
spec:
  storageClassName: synology-iscsi-retain
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
