apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data-pvc
spec:
  storageClassName: synology-iscsi-retain
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  securityContext:
    fsGroup: 33